version: "3"

tasks:
  run:
    cmds:
      - |
        echo "
         █████╗  ██╗ ██╗  ██╗ ██╗   ██╗  ██████╗
        ██╔══██╗ ██║ ██║ ██╔╝ ╚██╗ ██╔╝ ██╔═══██╗
        ███████║ ██║ █████╔╝   ╚████╔╝  ██║   ██║
        ██╔══██║ ██║ ██╔═██╗    ╚██╔╝   ██║   ██║
        ██║  ██║ ██║ ██║  ██╗    ██║    ╚██████╔╝
        ╚═╝  ╚═╝ ╚═╝ ╚═╝  ╚═╝    ╚═╝     ╚═════╝
        "
      - task: up

  up:
    deps:
      - task: firehose

  firehose:
    cmds:
      - npm run firehose

  companion:
    cmds:
      - npm run companion --config={{.CLI_ARGS}}
